### PR TITLE
New districts

### PR DESCRIPTION
**Pull request by captn3m0**
PR contains 2 commits:

1. To drop the Serial number column which makes diffs useless
2. Updates to the new dataset, just downloaded from the lgdirectory.

The [second commit](https://github.com/planemad/india-local-government-directory/commit/0aef3c9ac793000f01ab537db04d1b56b9cc6ee3) has a clean diff of new changes.

Here's a diff generated using csvdiff:

### Additions (24)

```diff
+ 28,ANDHRA PRADESH,745,Alluri Sitharama Raju,,0
+ 28,ANDHRA PRADESH,744,Anakapalli,,0
+ 28,ANDHRA PRADESH,753,Annamayya,,0
+ 28,ANDHRA PRADESH,750,Bapatla,,0
+ 28,ANDHRA PRADESH,748,Eluru,,0
+ 28,ANDHRA PRADESH,746,Kakinada,,0
+ 28,ANDHRA PRADESH,747,Konaseema,,0
+ 28,ANDHRA PRADESH,755,Nandyal,,0
+ 28,ANDHRA PRADESH,749,NTR,,0
+ 28,ANDHRA PRADESH,751,Palnadu,,0
+ 28,ANDHRA PRADESH,743,Parvathipuram Manyam,,0
+ 28,ANDHRA PRADESH,754,Sri Sathya Sai,,0
+ 28,ANDHRA PRADESH,752,Tirupati,,0
+ 18,ASSAM,756,TAMULPUR,,0
+ 22,CHHATTISGARH,759,KHAIRGARH CHHUIKHADAN GANDAI,,0
+ 22,CHHATTISGARH,760,MANENDRAGARH CHIRIMIRI BHARATPUR,,0
+ 22,CHHATTISGARH,761,MOHLA MANPUR AMBAGARH CHOUKI,,0
+ 22,CHHATTISGARH,762,SAKTI,,0
+ 22,CHHATTISGARH,763,SARANGARH BILAIGARH,,0
+ 17,MEGHALAYA,740,EASTERN WEST KHASI HILLS,,0
+ 13,NAGALAND,758,Chumoukedima,,0
+ 13,NAGALAND,757,Tseminyu,,0
+ 11,SIKKIM,741,Pakyong,,0
+ 11,SIKKIM,742,Soreng,,0
```

# Modifications (5)

```diff
- 22,CHHATTISGARH,645,GARIYABAND,,645
+ 22,CHHATTISGARH,645,GARIYABAND,,0
- 23,MADHYA PRADESH,409,HOSHANGABAD,37,449
+ 23,MADHYA PRADESH,409,NARMADAPURAM,37,449
- 11,SIKKIM,228,WEST DISTRICT,2,242
+ 11,SIKKIM,228,Gyalshing,2,242
- 11,SIKKIM,226,NORTH DISTRICT,1,241
+ 11,SIKKIM,226,Mangan,1,241
- 11,SIKKIM,227,SOUTH DISTRICT,3,243
+ 11,SIKKIM,227,Namchi,3,243
```

Attaching the raw files used:

- [allDistrictofIndia2022_12_14_13_01_37_318.xls](https://github.com/planemad/india-local-government-directory/files/10225505/allDistrictofIndia2022_12_14_13_01_37_318.xls)
- [allDistrictofIndia2022_12_14_13_01_11_452.pdf](https://github.com/planemad/india-local-government-directory/files/10225503/allDistrictofIndia2022_12_14_13_01_11_452.pdf)

### CODE REVIEW

**Comment by captn3m0** [comment]
@planemad Could this be merged?

**Comment by planemad** [comment]
Thank you @captn3m0 🙏 

Do note that https://ramseraph.github.io/opendata/lgd/ has daily dumps of LGD which could be useful. Are you seeing value in keeping this repository updated?

**Comment by captn3m0** [comment]
Having a repository to track is often easier (such as via a git submodule), which can be updated using tooling like dependabot.

The LGD daily dump is devoid of releases/diffs/changelogs, so harder to adopt.

**Comment by captn3m0** [comment]
Happy to join as a maintainer here, if you think that might help.

**Comment by planemad** [comment]
@captn3m0 👌 wonderful, have invited you as collaborator

**Comment by planemad** [comment]
> The LGD daily dump is devoid of releases/diffs/changelogs, so harder to adopt.

There is a changes.csv https://ramseraph.github.io/opendata/lgd/anatomy 

Maybe worth updating a monthly snapshot from https://ramseraph.github.io/opendata/lgd/ to this repository

**Pull request merged**
